version: "3.8"
services:
  postgres:
    container_name: jhub-postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: japanesehub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/table.sql:/docker-entrypoint-initdb.d/table.sql
  pgadmin:
    image: dpage/pgadmin4:4.27
    container_name: jhub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5555:80"