CREATE TABLE accounts (
	id SERIAL PRIMARY KEY,
  account VARCHAR(255) UNIQUE NOT NULL,
  msg VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  JLPT INT NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);